# **STAT6289 Statistical Deep Learning Homework 1**


## Problem 1



###(a) 
$h_1 = \frac{1}{1+e^{-(1.5\times 1+2.5\times 0+1\times 1)}} = \frac{1}{1+e^{-2.5}} = 0.9241$ 

$h_2 = \frac{1}{1+e^{-(2\times 1-1.5\times 0-3\times 1)}} = \frac{1}{1+e^{1}} = 0.2689$ 

$\hat{y} = \frac{1}{1+e^{-(-1\times 1+1\times 0.9241+0.5\times 0.2689)}} = \frac{1}{1+e^{-0.05855}} = 0.5146$

### (b)
Based on the the following equation: 

$E = \frac{1}{2}\left( y - \hat{y}\right)^2$

$\hat{y} = \frac{1}{1+e^{- \left(w_{\hat{y}b}b + w_{\hat{y}h_1}h_1 + w_{\hat{y}h_2}h_2\right)}} $ 

$h_1 = \frac{1}{1+e^{\left(w_{h_1b}b + w_{h_1x_1}x_1 + w_{h_1x_2}x_2\right)}}$ 

$h_2 = \frac{1}{1+e^{\left(w_{h_2b}b + w_{h_2x_1}x_1 + w_{h_2x_2}x_2\right)}}$ 

We can calculate the gradient in the following way: 

$\frac{\partial E }{\partial w_{\hat{y}b}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial w_{\hat{y}b}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})b = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 1 = -0.1212$
$\frac{\partial E }{\partial w_{\hat{y}h_1}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial w_{\hat{y}h_1}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})h_1 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 0.9241 = -0.1120$
$\frac{\partial E }{\partial w_{\hat{y}h_2}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial w_{\hat{y}h_2}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})h_2 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 0.2689 = -0.0326$
$\frac{\partial E }{\partial w_{h_1b}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_1}\cdot \frac{\partial h_1}{\partial w_{h_1b}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_1}\cdot h_1(1-h_1)b = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 1\times 0.9241(1-0.9241) \times 1 = -0.0085$
$\frac{\partial E }{\partial w_{h_1x_1}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_1}\cdot \frac{\partial h_1}{\partial w_{h_1x_1}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_1}\cdot h_1(1-h_1)x_1 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 1\times 0.9241(1-0.9241) \times 0 = 0$
$\frac{\partial E }{\partial w_{h_1x_2}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_1}\cdot \frac{\partial h_1}{\partial w_{h_1x_2}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_1}\cdot h_1(1-h_1)x_2 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 1\times 0.9241(1-0.9241) \times 1 = -0.0085$
$\frac{\partial E }{\partial w_{h_2b}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_2}\cdot \frac{\partial h_2}{\partial w_{h_2b}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_2}\cdot h_2(1-h_2)b = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 0.5\times 0.2689(1-0.2689) \times 1 = -0.0119$
$\frac{\partial E }{\partial w_{h_2x_1}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_2}\cdot \frac{\partial h_2}{\partial w_{h_2x_1}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_2}\cdot h_2(1-h_2)x_1 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 0.5\times 0.2689(1-0.2689) \times 0 = 0$
$\frac{\partial E }{\partial w_{h_2x_2}} = \frac{\partial E}{\partial \hat{y}}\cdot \frac{\partial \hat{y}}{\partial h_2}\cdot \frac{\partial h_2}{\partial w_{h_2x_2}} = -(y-\hat{y})\cdot \hat{y}(1-\hat{y})w_{\hat{y}h_2}\cdot h_2(1-h_2)x_2 = -(1 - 0.5146)\times 0.5146(1-0.5146)\times 0.5\times 0.2689(1-0.2689) \times 1 = -0.0119$ 

Therefore, we have the following updated weights:

$w_{\hat{y}b} = w_{\hat{y}b} - \alpha \frac{\partial E }{\partial w_{\hat{y}b}} = -1 - 0.1(-0.1212) = -0.9879$

$w_{\hat{y}h_1} = w_{\hat{y}h_1} - \alpha \frac{\partial E }{\partial w_{\hat{y}h_1}} = 1 - 0.1(-0.1120) = 1.0112$

$w_{\hat{y}h_2} = w_{\hat{y}h_2} - \alpha \frac{\partial E }{\partial w_{\hat{y}h_2}} = 0.5 - 0.1(-0.0326) = 0.5033$ 

$w_{h_1b} = w_{h_1b} - \alpha \frac{\partial E }{\partial w_{h_1b}} = 1.5 - 0.1(-0.0085) = 1.5009$ 

$w_{h_1x_1} = w_{h_1x_1} - \alpha \frac{\partial E }{\partial w_{h_1x_1}} = 2.5 - 0.1(0) = 2.5$ 

$w_{h_1x_2} = w_{h_1x_2} - \alpha \frac{\partial E }{\partial w_{h_1x_2}} = 1 - 0.1(-0.0085) = 1.0009$ 

$w_{h_2b} = w_{h_2b} - \alpha \frac{\partial E }{\partial w_{h_2b}} = 2 - 0.1(-0.0119) = 2.0012$ 

$w_{h_2x_1} = w_{h_2x_1} - \alpha \frac{\partial E }{\partial w_{h_2x_1}} = -1.5 - 0.1(0) = -1.5$ 

$w_{h_2x_2} = w_{h_2x_2} - \alpha \frac{\partial E }{\partial w_{h_2x_2}} = -3 - 0.1(-0.0119) = -2.9988$

## Problem 2

### Implementation of Pytorch tutorial


We first import the torch package.

In [2]:
import torch
print(torch.__version__)

1.6.0+cu101


#### 1. Baiscs


The followings are examples of one-dimensional and two-dimensional tensor.

In [6]:
# create a one-dimensional tensor
X = torch.tensor([123, 456, 789])
print(X)
print("Type of X is ", type(X))
print("Dimension os X is ", X.dim())
print("The shape of X is ", X.shape)

# get elements of a tensor
print("The first element of X is ", X[0])

# change element of a tensor
X[-1] = 999 #change he last element of X to 999
print(X)

tensor([123, 456, 789])
Type of X is  <class 'torch.Tensor'>
Dimension os X is  1
The shape of X is  torch.Size([3])
The first element of X is  tensor(123)
tensor([123, 456, 999])


In [9]:
# create a two-dimensional tensor
Y = torch.tensor([[123, 456, 789], [1, 2, 3]])
print(Y)
print("Dimension of Y is ", Y.dim())
print("The shape of Y is ", Y.shape)

# access and change elements of tensor
print("The second element of the first list of Y is ", Y[0, 1])
Y[1,2] = 999 #change the last element of the second list of Y to 999
print(Y)

tensor([[123, 456, 789],
        [  1,   2,   3]])
Dimension of Y is  2
The shape of Y is  torch.Size([2, 3])
The second element of the first list of Y is  tensor(456)
tensor([[123, 456, 789],
        [  1,   2, 999]])


PyTorch also provides methods to generate tensors of zeros and random numbers. The following are some examples.

In [12]:
# create a tensor of all zeros
a = torch.zeros(3, 2, 5)
print(a)

# create a 5 by 5 identity matrix
b = torch.eye(5)
print(b)

# create a tensor of random numbers
c = torch.rand(2, 3)
print(c)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[0.2580, 0.5420, 0.4270],
        [0.8249, 0.0851, 0.0886]])


PyTorch tries to guess a datatype when you create a tensor; functions that construct tensors typically have a dtype argument that you can use to explicitly specify a datatype.

In [14]:
# Default data type
a1 = torch.tensor([1, 2, 3])
a2 = torch.tensor([1., 2., 3.])
print("The data type of a1 is ", a1.dtype)
print("The data type of a2 is ", a2.dtype)

# Fix the data type
b1 = torch.tensor([1, 2, 3], dtype=torch.int64)
b2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(b1)
print(b2)


The data type of a1 is  torch.int64
The data type of a2 is  torch.float32
tensor([1, 2, 3])
tensor([1., 2., 3.], dtype=torch.float64)


#### 2. Tensor indexing

##### Slice indexing


In [15]:
X = torch.tensor([1, 2, 3, 4, 5, 6])
print(X)
print(X[2:4]) 
print(X[:4])
print(X[:])
print(X[1:4:2])
print(X[:-1])

tensor([1, 2, 3, 4, 5, 6])
tensor([3, 4])
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4, 5, 6])
tensor([2, 4])
tensor([1, 2, 3, 4, 5])


In [26]:
Y = torch.tensor([[1, 2, 3], [12, 34, 56], [123, 456, 789]])
print(Y)
print(Y[1, :]) #second row
print(Y[2, :]) #third row
print(Y[:, 1]) #second column
print(Y[:2, -1:]) #first two rows and last column

tensor([[  1,   2,   3],
        [ 12,  34,  56],
        [123, 456, 789]])
tensor([12, 34, 56])
tensor([123, 456, 789])
tensor([  2,  34, 456])
tensor([[ 3],
        [56]])


There are two ways of accessing a single row (or column) of a tensor.

In [27]:
row_r1 = Y[1, :]
row_r2 = Y[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = Y[:, 1]
col_r2 = Y[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


tensor([12, 34, 56]) torch.Size([3])
tensor([[12, 34, 56]]) torch.Size([1, 3])
tensor([  2,  34, 456]) torch.Size([3])
tensor([[  2],
        [ 34],
        [456]]) torch.Size([3, 1])


Slicing a tensor returns a view into the same data, so modifying it will also modify the original tensor. To avoid this, you can use the clone() method to make a copy of a tensor.

In [28]:
a = Y[0, :2]
b = Y[0, :2].clone()
print(a)
print(b)

Y[0, 0] = 10
a[1] = 100
print(a)
print(b)



tensor([1, 2])
tensor([1, 2])
tensor([ 10, 100])
tensor([1, 2])


We can use index arrays to index tensors.

In [37]:
X = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(X)

ind = [0,0,0,2,2,1,1,2,0]
print(X[ind, :])
print(X[:, ind])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [7, 8, 9],
        [7, 8, 9],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]])
tensor([[1, 1, 1, 3, 3, 2, 2, 3, 1],
        [4, 4, 4, 6, 6, 5, 5, 6, 4],
        [7, 7, 7, 9, 9, 8, 8, 9, 7]])


In [36]:
ind1 = [0, 1, 2]
print(X[ind1, ind1])
X[ind1, ind1] = torch.tensor([666, 233, 233])
print(X)


tensor([1, 5, 9])
tensor([[666,   2,   3],
        [  4, 233,   6],
        [  7,   8, 233]])


##### Boolen tensor indexing

In [40]:
X = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(X)

mask = (X > 5)
print(mask)
print(X[mask])

#change all elements less than or equal to 4 to zero
X[X <= 4] = 0
print(X)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([6, 7, 8, 9])
tensor([[0, 0, 0],
        [0, 5, 6],
        [7, 8, 9]])


#### 3. Reshaping operations

In [45]:
a = torch.tensor([[12, 34], [56, 78]])
print(a, a.shape)

a1 = a.view(4)
print(a1)

a2 = a.view(1,4)
print(a2)

a3 = a.view(4, 1)
print(a3)

a4 = a.view(2, 2)
print(a4)

tensor([[12, 34],
        [56, 78]]) torch.Size([2, 2])
tensor([12, 34, 56, 78])
tensor([[12, 34, 56, 78]])
tensor([[12],
        [34],
        [56],
        [78]])
tensor([[12, 34],
        [56, 78]])


In [44]:
a5 = a.view(-1, )
print(a5)

a6 = a.view(-1, 2)
print(a6)

tensor([12, 34, 56, 78])
tensor([[12, 34],
        [56, 78]])


In [48]:
a7 = a.view(-1)
a[1, 1] = 0
a7[2] = 10
print(a)
print(a7)

tensor([[12, 34],
        [10,  0]])
tensor([12, 34, 10,  0])


##### Swaping axes

In [50]:
X = torch.eye(5)
X[4, 0] = 233
print(X)

print(torch.t(X))
print(X.t())

tensor([[  1.,   0.,   0.,   0.,   0.],
        [  0.,   1.,   0.,   0.,   0.],
        [  0.,   0.,   1.,   0.,   0.],
        [  0.,   0.,   0.,   1.,   0.],
        [233.,   0.,   0.,   0.,   1.]])
tensor([[  1.,   0.,   0.,   0., 233.],
        [  0.,   1.,   0.,   0.,   0.],
        [  0.,   0.,   1.,   0.,   0.],
        [  0.,   0.,   0.,   1.,   0.],
        [  0.,   0.,   0.,   0.,   1.]])
tensor([[  1.,   0.,   0.,   0., 233.],
        [  0.,   1.,   0.,   0.,   0.],
        [  0.,   0.,   1.,   0.,   0.],
        [  0.,   0.,   0.,   1.,   0.],
        [  0.,   0.,   0.,   0.,   1.]])


For tensors with more than two dimensions, we can use the function torch.transpose to swap arbitrary dimensions, or the .permute method to arbitrarily permute dimensions:

In [54]:
X = torch.tensor([
                  [
                   [1,2], [3,4], [5,6]
                  ],
                  [
                   [11, 22], [33, 44], [55, 66]
                  ]
])
print(X, X.shape)

X1 = X.transpose(1, 2)
print(X1, X1.shape)

X2 = X.permute(1, 2, 0)
print(X2, X2.shape)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[11, 22],
         [33, 44],
         [55, 66]]]) torch.Size([2, 3, 2])
tensor([[[ 1,  3,  5],
         [ 2,  4,  6]],

        [[11, 33, 55],
         [22, 44, 66]]]) torch.Size([2, 2, 3])
tensor([[[ 1, 11],
         [ 2, 22]],

        [[ 3, 33],
         [ 4, 44]],

        [[ 5, 55],
         [ 6, 66]]]) torch.Size([3, 2, 2])


#### 4. tensor operations

In [8]:
# Some basic tensor operations
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
print(A)
print(B)

# elementwise addition of tensor
print(A+B)
print(torch.add(A, B))
print(A.add(B))

# elementwise subtraction of tensor
print(A-B)
print(torch.sub(A, B))
print(A.sub(B))

# elementwise product of tensor
print(A * B)
print(torch.mul(A, B))
print(A.mul(B))


# elementwise power of tensor
print(A ** B)
print(torch.pow(A, B))
print(A.pow(B))

# Some other operations
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(torch.log(A))
print(torch.sin(A))
print(torch.sinh(A))
print(torch.sqrt(A))
print(torch.square(A))
print(torch.inverse(A))


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])
tensor([[1, 2, 4],
        [4, 6, 6],
        [8, 8, 9]])
tensor([[1, 2, 4],
        [4, 6, 6],
        [8, 8, 9]])
tensor([[1, 2, 4],
        [4, 6, 6],
        [8, 8, 9]])
tensor([[1, 2, 2],
        [4, 4, 6],
        [6, 8, 9]])
tensor([[1, 2, 2],
        [4, 4, 6],
        [6, 8, 9]])
tensor([[1, 2, 2],
        [4, 4, 6],
        [6, 8, 9]])
tensor([[0, 0, 3],
        [0, 5, 0],
        [7, 0, 0]])
tensor([[0, 0, 3],
        [0, 5, 0],
        [7, 0, 0]])
tensor([[0, 0, 3],
        [0, 5, 0],
        [7, 0, 0]])
tensor([[1, 1, 3],
        [1, 5, 1],
        [7, 1, 1]])
tensor([[1, 1, 3],
        [1, 5, 1],
        [7, 1, 1]])
tensor([[1, 1, 3],
        [1, 5, 1],
        [7, 1, 1]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0

Reduction operations

In [9]:
print(A)
print(A.sum())
print(torch.sum(A))

# sum over row
print(A.sum(dim=1))
print(torch.sum(A, dim=1))
#sum over column
print(A.sum(dim=0))
print(torch.sum(A, dim=0))

# mean over row
print(A.mean(dim=1))
print(torch.mean(A, dim=1))
# mean over column
print(A.mean(dim=0))
print(torch.mean(A, dim=0))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(45.)
tensor(45.)
tensor([ 6., 15., 24.])
tensor([ 6., 15., 24.])
tensor([12., 15., 18.])
tensor([12., 15., 18.])
tensor([2., 5., 8.])
tensor([2., 5., 8.])
tensor([4., 5., 6.])
tensor([4., 5., 6.])


In [5]:
a = torch.randn(6, 7, 8, 9)
print(a.shape)

a1 = torch.mean(a, dim=1)
print(a1.shape)

a2 = torch.mean(a, dim = 3)
print(a2.shape)

torch.Size([6, 7, 8, 9])
torch.Size([6, 8, 9])
torch.Size([6, 7, 8])


##### Matrix operations

In [13]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([1., 2., 3.])

print(torch.dot(a, b))
print(a.dot(b))

A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32)
B = torch.eye(3, dtype=torch.float32)
print(torch.mm(A, B))

print(torch.mv(A, a))

tensor(14.)
tensor(14.)
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([14., 32., 50.])


#### 5. Broadcasting

In [17]:
a = torch.tensor([1, 233, 10])
# stack 4 copies of a on top of each other
print(a.repeat(4, 1))
print(a.repeat(4, 2))
print(a.repeat(4, 3))

tensor([[  1, 233,  10],
        [  1, 233,  10],
        [  1, 233,  10],
        [  1, 233,  10]])
tensor([[  1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10]])
tensor([[  1, 233,  10,   1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10,   1, 233,  10],
        [  1, 233,  10,   1, 233,  10,   1, 233,  10]])


In [20]:
# use broadcasting
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(x + a)
print(x + a.repeat(4, 1))
# these two ways should give the same results

# b = torch.tensor([1, 2])
# print(x + b)
# this cannot be done because of the shape is not the same

tensor([[  2, 235,  13],
        [  5, 238,  16],
        [  8, 241,  19],
        [ 11, 244,  22]])
tensor([[  2, 235,  13],
        [  5, 238,  16],
        [  8, 241,  19],
        [ 11, 244,  22]])
